### ISSUE TITLE
Search Form

### ISSUE THREAD

**Issue by ashleymullikin** [kabradshaw1/National-Parks#17]

**Comment by kabradshaw1** [comment]
HandleResultsSaved function still needs some work, if anyone wants to take a look at that.

**Comment by kabradshaw1** [comment]
Changing the search from activities to alerts on line 85 makes it fetch a different json that you can see in in the console.  We need to set up the display that starts on line 102 with some if statements, or find some method of making the display dynamic.

**Comment by kabradshaw1** [comment]
I think at some point we might want to consider moving the SearchForm component to the home page, or possibly another page, and making that call the results component that I moved into the SearchForm component.

**Comment by kabradshaw1** [comment]
Done enough.
