### ISSUE TITLE
Defining the API call further

### ISSUE THREAD

**Issue by ashleymullikin** [kabradshaw1/National-Parks#21]
To be done after more work done in other sections

**Comment by kabradshaw1** [comment]
I feel like this is kind of being addressed in the comment I put in the SearchForm.  We can no do api searches in the client/src/components/SearchForm on line 63 and it's getting passed into the fetch at the bottom of client/src/utils/API.  You can see the object we are storing to display by putting a console.log(data2) at line 32 of client/src/components/SearchForm.
